### ISSUE TITLE
Label support for emails & phones

### ISSUE THREAD

**Issue by tneotia** [s0nerik/fast_contacts#1]
Hi there! First want to say - absolutely excellent package, you don't lie, my time to fetch ~200 contacts went from 750ms to 100ms after I switched to this package. 

However one thing I would like to request is support for the "label" attribute for emails and phones, e.g. to know if the phone is home / work / mobile etc. This is the only functionality our app missed out on when migrating. If it could be added that would be great!

**Comment by s0nerik** [comment]
Hey @tneotia! Thanks for trying out the lib. :)

After a short research, it seems like this "label" thing is Android-specific. Aren't you looking for additional fields (like "Company" or "Address") for iOS as well?

Or, if you know of something that can be treated as a "label" for iOS - I'd be glad to learn that!

**Comment by tneotia** [comment]
Currently our app is Android only so I don't know too much about iOS, but it does seem that the alternative to labels on Android is the groups on iOS, which I saw in the changelog for flutter_contacts: https://pub.dev/packages/flutter_contacts/versions/1.1.1/changelog

Hope this helps!
