### ISSUE TITLE
Error : Type 'Uint8List' not found.

### ISSUE THREAD

**Issue by zackattack73** [s0nerik/fast_contacts#11]
Hello,
With version 3.0.0 and using your example, my app won't start and give the following error :

`[        ] ../../Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/fast_contacts-3.0.0/lib/src/fast_contacts.dart:93:17: Error: Type 'Uint8List' not found.
[   +1 ms]   static Future<Uint8List?> getContactImage(
[        ]                 ^^^^^^^^^
`

It seems like in your `fast_contact.dart` file you didn't use : import "dart:typed_data";

**Comment by s0nerik** [comment]
Should be fixed in 3.0.2
