### ISSUE TITLE
Contact first/last names are backwards for some users on v3.0.0+

### ISSUE THREAD

**Issue by tneotia** [s0nerik/fast_contacts#12]
This is something that a few of our app's users have been experiencing after we upgraded our dependencies. To narrow it down, I created a troubleshooting menu of sorts for them (uses RxDart):

```dart
final RxList<String> log = <String>[].obs;
showDialog(
    context: context,
    builder: (context) => AlertDialog(
      backgroundColor: context.theme.colorScheme.surface,
      contentPadding: const EdgeInsets.symmetric(horizontal: 20),
      titlePadding: const EdgeInsets.only(top: 15),
      title: Text("Fetching contacts...", style: context.theme.textTheme.titleLarge),
      content: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SizedBox(
          width: ns.width(context) * 4 / 5,
          height: context.height * 1 / 3,
          child: Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(25),
              color: context.theme.colorScheme.background,
            ),
            padding: const EdgeInsets.all(10),
            child: Obx(() => ListView.builder(
              physics: const AlwaysScrollableScrollPhysics(parent: BouncingScrollPhysics()),
              itemBuilder: (context, index) {
                return Text(
                  log[index],
                  style: TextStyle(
                    color: context.theme.colorScheme.onBackground,
                    fontSize: 10,
                  ),
                );
              },
              itemCount: log.length,
            )),
          ),
        ),
      ),
    )
);
final contacts = (await FastContacts.getAllContacts(
    fields: List<ContactField>.from(ContactField.values)
      ..removeWhere((e) => [ContactField.company, ContactField.department, ContactField.jobDescription, ContactField.emailLabels, ContactField.phoneLabels].contains(e))
)).map((e) => Contact(
  displayName: e.displayName,
  emails: e.emails.map((e) => e.address).toList(),
  phones: e.phones.map((e) => e.number).toList(),
  structuredName: e.structuredName == null ? null : StructuredName(
    namePrefix: e.structuredName!.namePrefix,
    givenName: e.structuredName!.givenName,
    middleName: e.structuredName!.middleName,
    familyName: e.structuredName!.familyName,
    nameSuffix: e.structuredName!.nameSuffix,
  ),
  id: e.id,
));
for (Contact c in contacts) {
  log.add("Contact ${c.id}: ${c.displayName} /// ${c.structuredName?.givenName} ${c.structuredName?.familyName}");
}
```

The reason I map to seemingly the same `Contact` class (its actually a different class) is because we have a custom Contact class that gets persisted to the database. However, that shouldn't affect the `displayName` field as that is mapped 1:1.

I had a user with the issue test this dialog out, and on the prints in the dialog they are seeing 

> Yeah got a long list that looks like this  contact ###: Last First /// First Last 

indicating that the structured name is right in pulling the first / last name, but the displayName has them reversed.

**Comment by s0nerik** [comment]
Hey, @tneotia. Could you please share which OS are you testing on? Or does it happen for both Android and iOS?

**Comment by tneotia** [comment]
Sorry I forgot to mention this is on Android.

**Comment by s0nerik** [comment]
@tneotia I think the issue you're describing is related to the user's locale.

[ContactsContract.ContactNameColumns](https://developer.android.com/reference/android/provider/ContactsContract.ContactNameColumns) contains multiple ways for fetching a contact's display name, suggesting that the display name requested from the Android is locale-dependent.

If you need a consistent order of First and Last names, please use `structuredName.givenName` and `structuredName.familyName` fields, concatenating them as needed.
