### ISSUE TITLE
Namespace not specified. Please specify a namespace in the module's build.gradle file like so

### ISSUE THREAD

**Issue by ettaegbe** [s0nerik/fast_contacts#14]
A problem occurred configuring project ':fast_contacts'.
[        ] > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
[        ]    > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:
[        ]      android {
[        ]          namespace 'com.example.namespace'
[        ]      }

**Comment by s0nerik** [comment]
Ready in 3.0.4: https://pub.dev/packages/fast_contacts/changelog#304
