### ISSUE TITLE
Duplicate phone numbers

### ISSUE THREAD

**Issue by danielnordh** [s0nerik/fast_contacts#2]
On Android, many contacts return duplicate phone numbers, formatted slightly differently.
This is not unique to this library, it also affects contacts_service. 

It seems to have to do with other apps storing the number again, for example WhatsApp Business storing the same number under 'Video call', 'Voice call' and 'Message'.

It is super annoying and basically not usable in production without filtering.

I suggest the library should:

Filter and compare each contact's phone numbers
If duplicates exist, only return ONE instance

**Comment by PcolBP** [comment]
As far as I am aware of it, deduplicate should happen in our code not in plugin. How will you decide which one should be deleted and which should stay if they have same number but different name? One name may say something to you but other may not, and default filtering may delete the one that is important to you. 

I think that we should decide, with our specific condition, and every condition in every company/project may be different so we cannot create global one inside plugin.

**Comment by s0nerik** [comment]
I can only agree with @PcolBP here. I don't think the library should decide which number is "right".
