### ISSUE TITLE
Build failed in fast_contact: ^3.1.5

### ISSUE THREAD

**Issue by Raj-impetrosys** [s0nerik/fast_contacts#26]
Check the below screenshot I'm getting this issue when upgraded from 3.1.4 to 3.1.5
<img width="1440" alt="Screenshot 2024-08-08 at 4 05 33 PM" src="https://github.com/user-attachments/assets/144ed753-4c0b-41ae-b0be-d2c47b893e5f">

**Comment by s0nerik** [comment]
Which Flutter version are you using?

**Comment by adnankadalayi** [comment]
I too have this problem. I am using 3.22.3

**Comment by adnankadalayi** [comment]
> Which Flutter version are you using?

I too have this problem. I am using 3.22.3. Upgraded package from 3.1.2 to 3.1.5

**Comment by s0nerik** [comment]
I believe pinning the plugin version to `3.1.4` or lower should fix the build problem on Flutter versions prior `3.24` while I'm trying to figure out how to deal with this issue.

@adnankadalayi @Raj-impetrosys please let me know if this helps.

I'll probably retract `3.1.5` and release a major version instead.

**Comment by Rajkumar07793** [comment]
> Which Flutter version are you using?

I'm using flutter 3.19.6

**Comment by Rajkumar07793** [comment]
Not having problem in 3.1.4 or lower the build failed in only 3.1.5

> I believe pinning the plugin version to `3.1.4` or lower should fix the build problem on Flutter versions prior `3.24` while I'm trying to figure out how to deal with this issue.
> 
> @adnankadalayi @Raj-impetrosys please let me know if this helps.
> 
> I'll probably retract `3.1.5` and release a major version instead.

**Comment by s0nerik** [comment]
To anyone looking into this issue after upgrading to Flutter 3.24:

Use `fast_contacts: ^4.0.0`.
