### ISSUE TITLE
Search for contact by id

### ISSUE THREAD

**Issue by zawadZwd** [s0nerik/fast_contacts#9]
Hi there
First of all, I want to thank you for the plugin, it's super helpful and works like a charm! The issue is not about a problem with plugin but what do you think ( if it is technically possible of course ) about searching a contact details, by passing the id ( similar like now for contact's image) ? 

I'm not gonna lie, it would have been super helpful for my project, but maybe for somebody else too 😅 

Just asking, thanks in advance!

**Comment by s0nerik** [comment]
Hey Zawad,
The plugin was designed to fetch all contacts with all data needed at once. So, the only option you have right now is to look for the contact within the returned contacts list yourself. Something as simple as `(await FastContacts.getAllContacts()).where((contact) => contact.id == <contact id>).first` will do it.

This said, though, it seems like what you might be after is the ability to fetch only some partial data for the contacts list, and more info for a specific contact. This is not currently possible but sounds like a good idea for a feature. I'll mark this as a feature request.

**Comment by zawadZwd** [comment]
Thank you for quick response!

> The plugin was designed to fetch all contacts with all data needed at once.

And Nintendo was designed for game cards in the begining 😅  - sorry for this poor joke, I could not resist...

> Something as simple as (await FastContacts.getAllContacts()).where((contact) => contact.id == <contact id>).first will do it.

This is quite nice workaround, but I think that in big contacts list it would have efficiency issue in compare with native search by id ( but I have no experience with java/kotlin )

I will look forward for the next features in your plugin 😄 

Best regards - Slava Ukraini!

**Comment by s0nerik** [comment]
Implemented in [v3.1.0](https://pub.dev/packages/fast_contacts/changelog#310)
